### ISSUE TITLE
Building the Docker image fails

### ISSUE THREAD

**Issue by glaforge** [vapor/toolbox#118]
I dockerized my app with the `vapor docker init`, but trying to build my docker image with `docker build -t myvapor .` I'm getting a failure and the trace points at:

```
--2016-12-21 09:20:03--  https://swift.org/builds/swift-3.0-release/ubuntu1404//-ubuntu14.04.tar.gz
Resolving swift.org (swift.org)... 169.45.67.140
Connecting to swift.org (swift.org)|169.45.67.140|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-12-21 09:20:09 ERROR 404: Not Found.

The command '/bin/sh -c SWIFT_ARCHIVE_NAME=$SWIFT_VERSION-$SWIFT_PLATFORM &&     SWIFT_URL=https://swift.org/builds/$SWIFT_BRANCH/$(echo "$SWIFT_PLATFORM" | tr -d .)/$SWIFT_VERSION/$SWIFT_ARCHIVE_NAME.tar.gz &&     wget $SWIFT_URL &&     wget $SWIFT_URL.sig &&     gpg --verify $SWIFT_ARCHIVE_NAME.tar.gz.sig &&     tar -xvzf $SWIFT_ARCHIVE_NAME.tar.gz --directory / --strip-components=1 &&     rm -rf $SWIFT_ARCHIVE_NAME* /tmp/* /var/tmp/*' returned a non-zero code: 8
```

I'm using the default Dockerfile generated, I didn't do any change.

**Comment by mz2** [comment]
I'm getting the same error.

**Comment by hactar** [comment]
So I had this error too, and it was caused by two problems:

1. I had a wrong version of  swift in the .swift-version file. I had to set the contents of that file to `swift-3.0.2-RELEASE`
2. I had to update the SWIFT_BRANCH in the Dockerfile. I updated the line to `ENV SWIFT_BRANCH swift-3.0.2-release`

Once I changed these two things my Dockerimage built (though I had to build it manually via the docker build command, because vapor docker build continued indefinitely)

**Comment by tannernelson** [comment]
https://github.com/vapor/toolbox/pull/132

**Comment by BrettRToomey** [comment]
Any updates?

**Comment by tanner0101** [comment]
We're removing docker support from toolbox.
