### ISSUE TITLE
Shell script installation hangs forever if already installed through homebrew

### ISSUE THREAD

**Issue by rudedogg** [vapor/toolbox#139]
If a user has installed Vapor Toolbox by running `brew install vapor/tap/toolbox`, but then attempts to run `curl -sL toolbox.vapor.sh | bash` the script will hang on the Installing step.

I ended up in this situation by installing Vapor several months ago, and forgetting how I installed it. To make sure I was using the latest Vapor Toolbox, I attempted to run ```vapor self update``` which would hang without any output.

I went to the docs to see how it was installed, and after checking https://vapor.github.io/documentation/getting-started/install-toolbox.html I assumed I installed it through the shell script. Re-running it would hang indefinitely on the `Installing` step. Uninstalling the `homebrew` version was the only way to get the new version successfully installed using the shell script.

May be worth consideration with https://github.com/vapor/documentation/issues/87

**Comment by patchthecode** [comment]
im also experiencing this

**Comment by vzsg** [comment]
The issue is actually caused by [`mv`](https://github.com/vapor/toolbox/blob/master/Sources/VaporToolbox/SelfInstall.swift#L53) showing a prompt, which is unhandled by the command and causes it to apparently hang:

```
11:15 $ mv /Users/zsolt/Library/Developer/Xcode/DerivedData/VaporToolbox-bnirzhuijlnpvebwlknghztjkpxt/Build/Products/Debug/Executable /usr/local/bin/vapor
override r-xr-xr-x  zsolt/staff for /usr/local/bin/vapor? (y/n [n]) 
```

Adding `-f` or `-n` should suppress the prompt with either a yes or no answer.

---

Sidenote: `vapor self update` and running the script manually are essentially the same thing. (Yet neither should be called after installing with homebrew, that will be the way forward anyway.)

**Comment by tanner0101** [comment]
Install through Homebrew or APT going forward. We'll be removing self update commands soon.

http://beta.docs.vapor.codes/getting-started/install-on-macos/#install-vapor
http://beta.docs.vapor.codes/getting-started/install-on-ubuntu/#apt-repo
