### ISSUE TITLE
executable missing dependencies

### ISSUE THREAD

**Issue by madsteer** [vapor/toolbox#251]
Per [this issue](https://github.com/vapor/homebrew-tap/issues/20) over on vapor/homebrew-tap I opted to go with the precompiled release.  So, I requested [this 3.1.10](
https://github.com/vapor/toolbox/releases/tag/3.1.10) build.  The README.txt in the tar.gz says to move the library files to the lib folder, but there aren't any library files in there.  Running the vapor command throws errors.  Please advise.

Thanks,

**Comment by grundoon** [comment]
No idea about the reason for this change, but the issue was introduced here: https://github.com/vapor/toolbox/commit/ae03392b7e5de6393fa1abd4208e2933becdddb3#diff-a3e1472db87afdd69b02af43b39e4916

**Comment by madsteer** [comment]
for what it's worth, I tried cloning this project and running
```swift
swift build -c release
```

It errors out
```bash
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "shim.h"
        ^
/Users/gmu9/dev/git/xcode/vapor/toolbox/.build/checkouts/ctls.git-3808886853717394823/shim.h:4:10: error: 'openssl/conf.h' file not found
#include <openssl/conf.h>
         ^
/Users/gmu9/dev/git/xcode/vapor/toolbox/.build/checkouts/crypto.git-3846566707428154072/Sources/Crypto/Cipher/Cipher+Method.swift:1:8: error: could not build Objective-C module 'CTLS'
import CTLS
       ^
. . .
error: terminated(1): /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-build-tool -f /Users/gmu9/dev/git/xcode/vapor/toolbox/.build/release.yaml main output:
```

this is on Mojave with xCode 10.1 installed

**Comment by grundoon** [comment]
Right, this is the `libressl` issue @vzsg mentioned over in the homebrew-tap discussion.

**Comment by BinaryHammer** [comment]
Since `vapor-beta` only uses `libressl` as dependency, I looked for an easy way to use this. Without building you can use the [homebrew bottle](https://bintray.com/homebrew/bottles/libressl), which is nothing more than an already precompiled version of `libressl` and put it in `/usr/local/`. The problem is that this interferes with the default installed `openssl`, since the binaries of `/usr/local/bin/` are used before the system binaries. macOS already has an `openssl` binary. Now everything on the mac will use the new one `/usr/local/bin/openssl` instead of `/usr/bin/openssl`.

The version of the default system version of openssl is LibreSSL 2.6.5, whereas the version of the homebrew version of openssl is 2.8.3. I do not know the implications of using a newer version, but I fear a small change could lead to subtle bugs with macOS services who definitaly need version 2.6.5. Even when installing libressl through homebrew it warns you and by defaults installs `libressl` without linking it to `/usr/local/bin`.

**Comment by tanner0101** [comment]
The next version of the toolbox will be built on Vapor 3+ which should be fine linking against system OpenSSL. I'll keep this issue open to track that. Generally, we should do a better job ensuring Toolbox executables work correctly when installed outside of Homebrew.

**Comment by madsteer** [comment]
What's the timeline for the next version (built on Vapor 3+) to be out?

Thanks,
