### ISSUE TITLE
Confusing help message and behaviour for run --port option

### ISSUE THREAD

**Issue by rderik** [vapor/toolbox#257]
First, thanks for the time every one of you put into Vapor such a cool project!

Now to the bug report.

When running the command:
`vapor -h run`

We get:

```
vapor --h run
Running project1 ...
Running default command: .build/debug/Run serve
Usage: .build/debug/Run [--hostname,-H] [--port,-p] [--bind,-b]

Begins serving the app over HTTP.

Options:
  hostname Set the hostname the server will run on.
      port Set the port the server will run on.
      bind Convenience for setting hostname and port together.
⚠️ [CommandError.excessInput: Too many arguments or unsupported options were supplied: ["--h=true"]]
Error: Run failed.
```

Which I expect should be the same as:
`vapor --help run`

but we get for `--help`:
```
 vapor --help run
Usage: vapor run [--exec]

Runs the compiled application.

Arguments:

Options:
     --exec The executable name.
```

Putting the difference in the text aside if I run the command:
`vapor run --port=8082`

it works but I get a Deprecation warning:
```
Running project1 ...
Running default command: .build/debug/Run serve
[Deprecated] --option=value syntax is deprecated. Please use --option value (with no =) instead.
Server starting on http://localhost:8082
```

That means I should run the command:
`vapor run --port 8082`

But I get the following error:

```
Running project1 ...
Usage: .build/debug/Run <command>

Commands:
   serve (default) Begins serving the app over HTTP.
    boot Boots the application's providers.
  routes Displays all registered routes.

Use `.build/debug/Run <command> [--help,-h]` for more information on a command.
⚠️ [CommandError.unknownCommand: Unknown command `8082`]
Error: Run failed
```

It seems to be an easy bug.
1.) find the discrepancy on when we call `-h` and `--help`
2.) Remove the one that is mistaken and route the two calls to the same action.
3.) Fix the help text to the correct version.
4.) Check the parsing of the options argsv and take into account that --port requires an additional parameter.

So if anyone has some time to walk me through the code base I would be glad to help fix it and once I'm more familiar with the code help with other easy fixes.

* Vapor Framework version: 3.1.1
* Vapor Toolbox version: 3.1.10
* OS version: Darwin Kernel Version 18.2.0

**Comment by rderik** [comment]
Thanks @tanner0101! I'll have a look around at the toolbox code and see if I can somehow help.

In my opinion, it should display the help of the `run` command, not the default `serve`. This, because the help will be executed mostly by new users and they won't know that `serve` is the default command and might be confused that they are getting the help for `serve`.

Let's wait and see if anyone else has any other opinion.

**Comment by tanner0101** [comment]
@rderik Sounds good. Make sure to look at https://github.com/vapor/toolbox/tree/18, that's where development is happening. :)

**Comment by tanner0101** [comment]
With Console 3.0, I think it's actually not currently possible to do a `vapor run` style, at least how it's implemented in the current toolbox that uses Console 2.0. 

In Console 3.0, you must explicitly declare each argument / option you would like the command to be able to accept. Any input to the command passed by a user that does not match will throw an error. 

This has been discussed in [Vapor chat](http://vapor.team) a bit, and I think the proper solution is to expand Console with a new `UnvalidatedCommand` protocol. Commands conforming to this protocol would not have to declare which arguments / options they accept, and would instead be forwarded any and all passed by the user. The `vapor run` command could utilize this protocol to act as a passthrough command, passing everything it receives directly to `swift run Run` (doing mutations on the options / arguments if needed). 

However, `UnvalidatedCommand` should be opened as a new issue on vapor/console. This issue in particular is about whether `-h` should trigger help for the `vapor run` command itself, or for the command that `vapor run` is forwarding to. 

Your comment on this issue was:

> In my opinion, it should display the help of the `run` command, not the default `serve`.

My opinion would be that `-h` should actually pass on to the `serve` command. As a new user to Vapor, I would have been introduced to `vapor run` as a way to boot and run my server. If I want to change which port I'm running, it's likely I would do `vapor run -h` to get some information about which flags are available. It might be confusing if this pulled up the help for the actual run command.

However, if in the help for the run command, we can explain the difference between `vapor run -h` and `vapor run serve -h`, that might be a good compromise.

**Comment by rderik** [comment]
I agree that would be a good compromise.

We could change the error message to:

```
Runs the compiled application.

By default `run` calls the default command `serve`. To view help message for `serve` command run the following:
`vapor run serve --help`
```

Now, I don't know if this happens only on my installation but when I run:
`vapor run serve --help`
I still get the run's help, not the serve's help, only if I use:
`vapor run serve -h`
I get serve's help but it shows an error at the end:
```
⚠️ [CommandError.excessInput: Too many arguments or unsupported options were supplied: ["--h=true"]]
Error: Run failed.```

Can you check if it happens for you too?

**Comment by tanner0101** [comment]
> I agree that would be a good compromise.

Cool, let's shoot for that behavior then once vapor/console#90 is resolved.

> I get serve's help but it shows an error at the end:

Ah, makes sense that would happen. I believe Console 3.0 added support for `-h`. So the current toolbox, which uses Console 2.0, does not recognize the `-h` short flag and passes it to the application adding on the old `=true` syntax. This will be fixed in the next toolbox release when we can drop support for the old `--foo=bar` syntax.

**Comment by tanner0101** [comment]
`vapor run` now simply passes all flags to the underlying Vapor package.
