### ISSUE TITLE
Invalid docker-compose.yml

### ISSUE THREAD

**Issue by grosch** [vapor/toolbox#334]
When giving a project name which includes capitalization the docker-compose.yml no longer works. Please force lowercase in the image names of the docker-compose.yml file.

**Comment by tanner0101** [comment]
My current thinking for implementing this is to just convert the name to kebab-case and use that everywhere. The name is currently used in:

- Package.swift "name"
- Docker compose file

In both of these places, kebab case is recommended. But the package.swift file is probably more controversial since it affects how the Git URL should be named. SPM requires that the repo name match the Package.swift name. SwiftNIO and Vapor both follow kebab-case naming. So it would make sense to me at least that the Vapor toolbox would promote this pattern, but I'm not sure we should force that on the user.

**Comment by grosch** [comment]
I'd prefer you didn't impose that.  The person should be able to choose their casing.  Companies might have naming rules, for example, and we shouldn't make it painful for them to "fix" that.  I think for the docker part it's fine to use kebab as that's not really "visible" anywhere.

**Comment by gwynne** [comment]
Strongly concur with @grosch here.

**Comment by marzvrover** [comment]
I just ran into this issue and was about to create a PR to solve this, however, I noticed this issue https://github.com/vapor/template/issues/29 where they did submit a PR to this repo (https://github.com/vapor/toolbox/pull/323) and the template repo (https://github.com/vapor/template/pull/30). I am wondering why those PRs were not merged. If there is additional work to them you'd like to see I'd be glad to fix them.

**Comment by gwynne** [comment]
@marzvrover It looks like Tanner closed the PRs because the original author did not update them per the discussion in vapor/template#29 (at least, that's my best guess). If you want to finish what was started there, I'll be glad to review and merge as appropriate.

**Comment by marzvrover** [comment]
@gwynne PR #353 and https://github.com/vapor/template/pull/45 are ready to reviewed
